### ISSUE TITLE
Search asynchronously

### ISSUE THREAD

**Issue by lucaswerkmeister** [lucaswerkmeister/linkStackTrace#3]
Blocking the UI thread for the search is Really Bad™. I’ll need to think a bit about how we preserve the order of the stack trace, but it should definitely be possible.

**Comment by lucaswerkmeister** [comment]
A few weeks ago, I read about the new JS promises and how they could be used to get a blog that asynchronously loads its content, but still keeps it in the right order. We might be able to use that.

**Comment by lucaswerkmeister** [comment]
No, I don’t think Promises will work. The caching still needs to work, which means that we can’t just fire off the requests and then collect the results.

I think we’ll need a three-phase approach:
1. Collect the lines+numbers / files
2. Send the requests – increment a counter, and the last request to return will execute phase 3 in its callback
3. Construct the stacktrace and call the return callback

Now, for the return type of the `linkStacktrace` function, we could actually use a Promise – on the other hand, Promises are a pretty new technology that isn’t supported at all in IE (not that I care about that) and were only enabled by default in Firefox 29.0.1 (which is now the latest release, and I don’t particularly care about the people who reverted to 28 because of Australis :-P).

**Comment by lucaswerkmeister** [comment]
Linking

```
Note: JBoss Modules version 1.1.3.GA
ceylon test: null
java.util.ConcurrentModificationException
at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1115)
at java.util.TreeMap$KeyIterator.next(TreeMap.java:1169)
at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getModuleList(Metamodel.java:762)
at ceylon.language.meta.modules_.getList(modules_.java:28)
at ceylon.test.internal.findCandidatesInModuleLiteral_.findCandidatesInModuleLiteral(TestRunnerImpl.ceylon:252)
at ceylon.test.internal.findCandidatesInTypeLiteral_.findCandidatesInTypeLiteral(TestRunnerImpl.ceylon:224)
at ceylon.test.internal.findCandidates_.findCandidates(TestRunnerImpl.ceylon:171)
at ceylon.test.internal.createExecutors_.createExecutors(TestRunnerImpl.ceylon:60)
at ceylon.test.internal.TestRunnerImpl.initExecutors$priv$(TestRunnerImpl.ceylon:36)
at ceylon.test.internal.TestRunnerImpl.(TestRunnerImpl.ceylon:39)
at ceylon.test.createTestRunner_.createTestRunner(TestRunner.ceylon:50)
at ceylon.test.createTestRunner_.createTestRunner(TestRunner.ceylon)
at com.redhat.ceylon.test.Runner.run(tool.ceylon:103)
at com.redhat.ceylon.test.run_.run(tool.ceylon:42)
<-- snip -->
```

takes about 1.1 – 1.4 seconds. I hope async searching will improve that.

**Comment by lucaswerkmeister** [comment]
Current plan for the “pipeline”:
1. Stacktrace → lines. Trivial.
2. Line → [LineFormat, File?, Line]. LineFormat is a string where "filename", surrounded by null bytes, is replaced by a URL to the file. File? is a file name string to be searched, or `null` if no file name should be searched. Line is a “plain” line that is used if File? is `null` or can’t be found in the search. Done mostly with the existing regex.
3. Searching. Collect the File?s (no duplicates), then fire off the requests. The callbacks will increase a counter, and the callback which finds the last result will start the rest of the pipeline. If the rate limit is hit, save it in a toplevel function-scoped variable.
4. [LineFormat, File?, Line] → Line. If File? exists and the file was found, insert it into LineFormat, otherwise use Line.
5. Lines → linked stacktrace. Trivial.

Note that there no longer is a cache involved; the effect of the current cache is achieved by removing duplicates in 3. (We could also insert a new, user/repo-scoped cache between 2 and 3 – that is, have a map "user/repo → cache", and query the correct cache to pre-process the lines.)

**Comment by lucaswerkmeister** [comment]
New signature:

``` js
function linkStacktrace(oauthToken, stackTrace, userOrRepo, function(result, rateLimitReset))
```

where the fourth argument is called when finished.

**Comment by lucaswerkmeister** [comment]
> […] takes about 1.1 – 1.4 seconds.

Scratch that. It can take over 2 seconds on a “cold start” for GitHub – it seems GitHub does some caching on their side as well (repository already in some server’s RAM or something like that).

**Comment by lucaswerkmeister** [comment]
Great success! Linking that stacktrace now takes ~0.9 seconds when GitHub is “warmed up”.

**Comment by lucaswerkmeister** [comment]
I’ll need to investigate that “warming up” a bit more – according to Firefox, some requests take over 1.5 seconds in the “Connecting” phase! Maybe I can reuse the connection?

**Comment by lucaswerkmeister** [comment]
Alright, it seems that the long requests always spend the bulk of their time in “Connecting” – up to 3 seconds!

But I’m not sure if I can do anything about that.
